name: Build and test for Ubuntu latest

on: [push, pull_request]

jobs:
  build:
    name: Build and install dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        openresty-version: [1.17.8.2]
        luarocks-version: [3.7.0]

    steps:
      - name: Checkout lua-resty-healthcheck
        uses: actions/checkout@v2

      - name: Update and install OS dependencies
        run: sudo apt-get update && sudo apt-get install -y libssl-dev ssl-cert

      - name: Set environment variables
        env:
          LUAROCKS_VER: ${{ matrix.luarocks-version }}
          OPENRESTY_VER: ${{ matrix.openresty-version }}
        run: |
          echo "DOWNLOAD_PATH=$HOME/download-root" >> $GITHUB_ENV
          echo "INSTALL_PATH=$HOME/install-root" >> $GITHUB_ENV
          echo "LUAROCKS_VER=$LUAROCKS_VER" >> $GITHUB_ENV
          echo "OPENRESTY_VER=$OPENRESTY_VER" >> $GITHUB_ENV
          export LUAROCKS_PREFIX=$INSTALL_PATH/luarocks-$LUAROCKS_VER
          echo "LUAROCKS_PREFIX=$LUAROCKS_PREFIX" >> $GITHUB_ENV
          export OPENRESTY_PREFIX=$INSTALL_PATH/openresty-$OPENRESTY_VER
          echo "OPENRESTY_PREFIX=$OPENRESTY_PREFIX" >> $GITHUB_ENV
          echo "PATH=$LUAROCKS_PREFIX/bin:$OPENRESTY_PREFIX/nginx/sbin:$PATH" >> $GITHUB_ENV

      - name: Lookup build cache
        uses: actions/cache@v2
        id: cache-deps
        with:
          path: ${{ env.INSTALL_PATH }}
          key: ${{ runner.os }}-${{ hashFiles('.github/workflows/latest_os.yml') }}

      - name: Create needed paths
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          mkdir $DOWNLOAD_PATH
          mkdir $INSTALL_PATH

      - name: Build and install OpenResty ${{ matrix.openresty-version }}
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          if [ ! -d $INSTALL_PATH/openresty-$OPENRESTY_VER ];
          then
            pushd $DOWNLOAD_PATH
            echo "Downloading from http://openresty.org/download/openresty-$OPENRESTY_VER.tar.gz"
            wget -O $DOWNLOAD_PATH/openresty-$OPENRESTY_VER.tar.gz http://openresty.org/download/openresty-$OPENRESTY_VER.tar.gz
            echo "tar -zxf $DOWNLOAD_PATH/openresty-$OPENRESTY_VER.tar.gz"
            tar -zxf $DOWNLOAD_PATH/openresty-$OPENRESTY_VER.tar.gz
            echo "result: $?"
            pushd openresty-$OPENRESTY_VER
            ./configure --prefix=$OPENRESTY_PREFIX
            make
            make install
            popd
            popd
          fi

      - name: Build and install LuaRocks ${{ matrix.luarocks-version }}
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          if [ ! -d $INSTALL_PATH/luarocks-$LUAROCKS_VER ];
          then
            pushd $DOWNLOAD_PATH
            echo "Downloading from https://luarocks.github.io/luarocks/releases/luarocks-$LUAROCKS_VER.tar.gz"
            wget -O $DOWNLOAD_PATH/luarocks-$LUAROCKS_VER.tar.gz https://luarocks.github.io/luarocks/releases/luarocks-$LUAROCKS_VER.tar.gz
            tar -zxf $DOWNLOAD_PATH/luarocks-$LUAROCKS_VER.tar.gz
            pushd luarocks-$LUAROCKS_VER
            ./configure --with-lua=$OPENRESTY_PREFIX/luajit --with-lua-include=$OPENRESTY_PREFIX/luajit/include/luajit-2.1 --lua-suffix=jit
            make build
            sudo make install
            popd
            sudo luarocks install luacheck
            popd
          fi

      - name: Install Test::NGINX
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          if [ ! -f $DOWNLOAD_PATH/cpanm ];
          then
            wget -O $DOWNLOAD_PATH/cpanm https://cpanmin.us/
            chmod +x $DOWNLOAD_PATH/cpanm
            $DOWNLOAD_PATH/cpanm --notest --local-lib=$INSTALL_PATH/perl5 local::lib && eval $(perl -I $INSTALL_PATH/perl5/lib/perl5/ -Mlocal::lib)
            $DOWNLOAD_PATH/cpanm --notest Test::Nginx
            $DOWNLOAD_PATH/cpanm --notest Test::Nginx::Socket::Lua
          fi

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set environment variables
        env:
          LUAROCKS_VER: ${{ matrix.luarocks-version }}
          OPENRESTY_VER: ${{ matrix.openresty-version }}
        run: |
          echo "DOWNLOAD_PATH=$HOME/download-root" >> $GITHUB_ENV
          echo "INSTALL_PATH=$HOME/install-root" >> $GITHUB_ENV
          echo "LUAROCKS_VER=$LUAROCKS_VER" >> $GITHUB_ENV
          echo "OPENRESTY_VER=$OPENRESTY_VER" >> $GITHUB_ENV
          export LUAROCKS_PREFIX=$INSTALL_PATH/luarocks-$LUAROCKS_VER
          echo "LUAROCKS_PREFIX=$LUAROCKS_PREFIX" >> $GITHUB_ENV
          export OPENRESTY_PREFIX=$INSTALL_PATH/openresty-$OPENRESTY_VER
          echo "OPENRESTY_PREFIX=$OPENRESTY_PREFIX" >> $GITHUB_ENV
          echo "PATH=$LUAROCKS_PREFIX/bin:$OPENRESTY_PREFIX/nginx/sbin:$PATH" >> $GITHUB_ENV

      - name: Lookup build cache
        uses: actions/cache@v2
        id: cache-deps
        with:
          path: ${{ env.INSTALL_PATH }}
          key: ${{ runner.os }}-${{ hashFiles('.github/workflows/latest_os.yml') }}

      - name: Lint code
        run: |
          eval `luarocks path`
          luacheck lib

  install:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set environment variables
        env:
          LUAROCKS_VER: ${{ matrix.luarocks-version }}
          OPENRESTY_VER: ${{ matrix.openresty-version }}
        run: |
          echo "DOWNLOAD_PATH=$HOME/download-root" >> $GITHUB_ENV
          echo "INSTALL_PATH=$HOME/install-root" >> $GITHUB_ENV
          echo "LUAROCKS_VER=$LUAROCKS_VER" >> $GITHUB_ENV
          echo "OPENRESTY_VER=$OPENRESTY_VER" >> $GITHUB_ENV
          export LUAROCKS_PREFIX=$INSTALL_PATH/luarocks-$LUAROCKS_VER
          echo "LUAROCKS_PREFIX=$LUAROCKS_PREFIX" >> $GITHUB_ENV
          export OPENRESTY_PREFIX=$INSTALL_PATH/openresty-$OPENRESTY_VER
          echo "OPENRESTY_PREFIX=$OPENRESTY_PREFIX" >> $GITHUB_ENV
          echo "PATH=$LUAROCKS_PREFIX/bin:$OPENRESTY_PREFIX/nginx/sbin:$PATH" >> $GITHUB_ENV

      - name: Lookup build cache
        uses: actions/cache@v2
        id: cache-deps
        with:
          path: ${{ env.INSTALL_PATH }}
          key: ${{ runner.os }}-${{ hashFiles('.github/workflows/latest_os.yml') }}

      - name: Install lua-resty-healthcheck
        run: sudo luarocks make

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Set environment variables
        env:
          LUAROCKS_VER: ${{ matrix.luarocks-version }}
          OPENRESTY_VER: ${{ matrix.openresty-version }}
        run: |
          echo "DOWNLOAD_PATH=$HOME/download-root" >> $GITHUB_ENV
          echo "INSTALL_PATH=$HOME/install-root" >> $GITHUB_ENV
          echo "LUAROCKS_VER=$LUAROCKS_VER" >> $GITHUB_ENV
          echo "OPENRESTY_VER=$OPENRESTY_VER" >> $GITHUB_ENV
          export LUAROCKS_PREFIX=$INSTALL_PATH/luarocks-$LUAROCKS_VER
          echo "LUAROCKS_PREFIX=$LUAROCKS_PREFIX" >> $GITHUB_ENV
          export OPENRESTY_PREFIX=$INSTALL_PATH/openresty-$OPENRESTY_VER
          echo "OPENRESTY_PREFIX=$OPENRESTY_PREFIX" >> $GITHUB_ENV
          echo "PATH=$LUAROCKS_PREFIX/bin:$OPENRESTY_PREFIX/nginx/sbin:$PATH" >> $GITHUB_ENV

      - name: Lookup build cache
        uses: actions/cache@v2
        id: cache-deps
        with:
          path: ${{ env.INSTALL_PATH }}
          key: ${{ runner.os }}-${{ hashFiles('.github/workflows/latest_os.yml') }}

      - name: Run tests
        run: |
          eval `luarocks path`
          eval $(perl -I $INSTALL_PATH/perl5/lib/perl5/ -Mlocal::lib)
          TEST_NGINX_RANDOMIZE=1 prove -r t
